# CI file

name: Build libultra

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request_target]

jobs:
  build_repo:
    name: Build repo
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        version: [L] # 
        suffix: [~, _d, _rom]

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Get ready for SDK
      run: ./.github/scripts/sdkinst.sh
      shell: bash

    - name: Update apt
      run: sudo apt update -y
    
    - name: Install SDK packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: build-essential python3 binutils-mips-n64 gcc-mips-n64 newlib-mips-n64 n64sdk makemask root-compatibility-environment
          version: 1.0

    - name: Build libultra${{ matrix.suffix }} ${{ matrix.version }}
      run: make -j $(nproc) VERSION=libultra${{ matrix.suffix }}
